version: 2

jobs:
  build:
    docker:
      - image: cimg/node:16.4.0

    steps:
      - checkout

      - run: echo "build project"
      
      - run: yarn install

      - run:
          name: Install Rover
          command: |
            # Download and install Rover
            # This is pinned to a specific version for predictability in CI
            curl -sSL https://rover.apollo.dev/nix/v0.8.1 | sh

            # This allows the PATH changes to persist to the next `run` step
            echo 'export PATH=$HOME/.rover/bin:$PATH' >> $BASH_ENV

      # Start the GraphQL server.  If a different command is used to
      # start the server, use it in place of `npm start` here.
      - run:
          name: Starting server
          command: yarn start
          background: true

      # make sure the server has enough time to start up before running
      # commands against it
      - run: sleep 5

      # When running on the 'main' branch, push the latest version
      # of the schema to Apollo Studio.
      - run: |
          if [ "${CIRCLE_BRANCH}" == "main" ]; then
            rover subgraph publish my-graph@my-variant \
              --schema ./schema.graphql \
              --name locations
          fi


# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build